//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_TESTEntities : DbContext
    {
        public DB_TESTEntities()
            : base("name=DB_TESTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_data> tbl_data { get; set; }
        public virtual DbSet<tbl_imagen> tbl_imagen { get; set; }

        public System.Data.Entity.DbSet<App.Models.ViewModels.FacturaViewModel> FacturaViewModels { get; set; }
    }
}
