//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_data
    {
        public int P_id { get; set; }
        public string P_name { get; set; }
        public string P_DES { get; set; }
        public string P_IMAGE { get; set; }
        public byte[] img { get; set; }
    }
}
